[package]
name = "stormybackend"
description = "Main binary for running the stormy backend, coordinates parsing of sites, sending data to DB"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stormycore = {path = "../../lib/stormycore"}
stormyscraper = {path = "../../lib/stormyscraper"}
