name: CI

on:
  push:
  pull_request:

jobs:
  cargo-fmt:
    name: "cargo fmt"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: "Install rustfmt"
        run: rustup component add rustfmt
      - run: cargo fmt --all --check

  cargo-clippy:
    name: "cargo clippy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: "Install clippy"
        run: rustup component add clippy
      - run: cargo clippy
  
  cargo-test:
    name: "cargo test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "cargo test"
        run: cargo test


